[package]
name = "climo"
version = "0.0.1"
authors = ["kwangin.jung <inylove82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
clipboard = "0.5.0"
sled = "0.34.6"

