[package]
name = "climo"
version = "0.0.1"
authors = ["kwangin.jung <inylove82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
clipboard = "0.5.0"
bawikv = { path = "../bawikv" }
